version: '3.8'

services:
  db:
    image: postgres:13
    container_name: plus_appointments_database
    environment:
      POSTGRES_DB: plus_appointments_database
      POSTGRES_USER: hieple
      POSTGRES_PASSWORD: hieple
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: plus_appointments_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plus_appointments_web
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=plus_appointments_database;Username=hieple;Password=hieple
      - ConnectionStrings__RedisConnection=plus_appointments_redis:6379

volumes:
  db_data:
  redis_data:
