START TRANSACTION;

ALTER TABLE users DROP COLUMN refresh_token;

ALTER TABLE users DROP COLUMN refresh_token_expiry_time;

CREATE TABLE user_refresh_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token text NOT NULL,
    expiry_time timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_refresh_tokens" PRIMARY KEY (id),
    CONSTRAINT "FK_user_refresh_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_user_refresh_tokens_token" ON user_refresh_tokens (token);

CREATE INDEX "IX_user_refresh_tokens_user_id" ON user_refresh_tokens (user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240812195100_RemoveRefreshTokenColumnsAndAddUserRefreshTokenTable', '8.0.5');

COMMIT;

