name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_IMAGE_NAME_BE }}:latest
          pull: true

      # Step 6: SSH into Frontend (FE) as Jump Host and deploy to Backend (BE)
      - name: Deploy to Backend via Frontend Jumphost
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FE_SERVER_IP }}
          username: ${{ secrets.FE_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Add the SSH key
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions_key_unix
            chmod 600 ~/.ssh/github_actions_key_unix

            # Print the bird from the FE server
            echo "SSH Connection to Frontend Successful"
            uname -a  # Prints system information (bird) for the FE server

            # SSH into the backend instance using the jumphost
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions_key_unix ec2-user@${{ secrets.BE_SERVER_IP }} << 'EOF'
              echo "SSH Connection to Backend Successful"

              # Docker commands on the BE instance
              docker system prune -a -f
              docker pull ${{ secrets.DOCKER_IMAGE_NAME_BE }}:latest
              docker stop plus_appointments_web || true
              docker rm plus_appointments_web || true
              docker run -d --name plus_appointments_web -p 8080:8080 ${{ secrets.DOCKER_IMAGE_NAME_BE }}:latest
            EOF
      
